const longformsTable = {
    "am not": "ain't",
    "are not": "ain't",
    "cannot": "can't",
    "could have": "could've",
    "could not have": "couldn't've",
    "could not": "couldn't",
    "did not": "didn't",
    "do not": "don't",
    "does not": "doesn't",
    "going to": "gonna",
    "got a": "gotta",
    "got an": "gotta",
    "got to": "gotta",
    "had not have": "hadn't've",
    "had not": "hadn't",
    "has not": "hasn't",
    "have not": "haven't",
    "he had": "he'd",
    "he has": "he's",
    "he is": "he's",
    "he shall": "he'll",
    "he will": "he'll",
    "he would have": "he'd've",
    "he would": "he'd",
    "how did": "how'd",
    "how does": "how's",
    "how has": "how's",
    "how is": "how's",
    "how will": "how'll",
    "how would": "how'd",
    "i am": "i'm",
    "i had": "i'd",
    "i have not": "i'ven't",
    "i have": "i've",
    "i shall": "i'll",
    "i will": "i'll",
    "i would have": "i'd've",
    "i would": "i'd",
    "is not": "isn't",
    "it has": "it's",
    "it is": "it's",
    "it shall": "it'll",
    "it will": "it'll",
    "it would have": "it'd've",
    "it would": "it'd",
    "let us": "let's",
    "might have": "might've",
    "might not have": "mightn't've",
    "might not": "mightn't",
    "must have": "must've",
    "must not": "mustn't",
    "need not": "needn't",
    "not have": "not've",
    "old": "ol'",
    "ought not": "oughtn't",
    "shall not": "shan't",
    "she had": "she'd",
    "she has": "she's",
    "she is": "she's",
    "she shall": "she'll",
    "she will": "she'll",
    "she would have": "she'd've",
    "she would": "she'd",
    "should have": "should've",
    "should not have": "shouldn't've",
    "should not": "shouldn't",
    "somebody had": "somebody'd",
    "somebody has": "somebody's",
    "somebody is": "somebody's",
    "somebody will have": "somebody'll've",
    "somebody will": "somebody'll",
    "somebody would have": "somebody'd've",
    "somebody would": "somebody'd",
    "someone had": "someone'd",
    "someone is": "someone's",
    "someone will": "someone'll",
    "someone would have": "someone'd've",
    "someone would": "someone'd",
    "something had": "something'd",
    "something has": "something's",
    "something is": "something's",
    "something will": "something'll",
    "something would have": "something'd've",
    "something would": "something'd",
    "someone has": "someone's",
    "that had": "that'd",
    "that has": "that's",
    "that is": "that's",
    "that shall": "that'll",
    "that will": "that'll",
    "that would": "that'd",
    "there are": "there're",
    "there had": "there'd",
    "there has": "there's",
    "there is": "there's",
    "there would have": "there'd've",
    "there would": "there'd",
    "they are": "they're",
    "they had": "they'd",
    "they have not": "they'ven't",
    "they have": "they've",
    "they shall": "they'll",
    "they will": "they'll",
    "they would have": "they'd've",
    "they would": "they'd",
    "want a": "wanna",
    "want an": "wanna",
    "want to": "wanna",
    "was not": "wasn't",
    "we are": "we're",
    "we had": "we'd",
    "we have": "we've",
    "we will": "we'll",
    "we would have": "we'd've",
    "we would not have": "we'dn't've",
    "we would": "we'd",
    "were not": "weren't",
    "what are": "what're",
    "what did": "what'd",
    "what does": "what's",
    "what has": "what's",
    "what have": "what've",
    "what is": "what's",
    "what shall": "what'll",
    "what will": "what'll",
    "when has": "when's",
    "when is": "when's",
    "where are": "when're",
    "where did": "where'd",
    "where does": "where's",
    "where has": "where's",
    "where have": "where've",
    "where is": "where's",
    "who are": "who're",
    "who did": "who'd",
    "who does": "who's",
    "who had": "who'd",
    "who has": "who's",
    "who have": "who've",
    "who is": "who's",
    "who shall": "who'll",
    "who will": "who'll",
    "who would have": "who'd've",
    "who would": "who'd",
    "why are": "why're",
    "why did": "why'd",
    "why does": "why's",
    "why has": "why's",
    "why have": "why've",
    "why is": "why's",
    "why will": "why'll",
    "will have": "will've",
    "will not have": "won't've",
    "will not": "won't",
    "would have": "would've",
    "would not have": "wouldn't've",
    "would not": "wouldn't",
    "you all have not": "y'all'ven't",
    "you all have": "y'all've",
    "you all will have": "y'all'll've",
    "you all will": "y'all'll",
    "you all would have": "y'all'd've",
    "you all would not have": "y'all'dn't've",
    "you all": "y'all",
    "you are not": "you'ren't",
    "you are": "you're",
    "you had": "you'd",
    "you have not": "you'ven't",
    "you have": "you've",
    "you shall": "you'll",
    "you will": "you'll",
    "you would have": "you'd've",
    "you would": "you'd"
}

export default longformsTable
